### ISSUE TITLE
Interactive workflow MVP to build, configure, and run model simulations

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/.github-private#36]
Task tracking for a first-pass MVP version of a computational workflow graph. A computational workflow consists of edges/nodes that be tied together and execute.

- [x] (Shawn) Basic infinite canvas component to handle with zooming/panning and support for multiple layers, debugging visuals
- [x] (Edwin/Manfred/Daniel) Discussions/decisions on data structures, serialization, deserialization and execution path
- [x] (Edwin) Data layer and background layer work: Drawing nodes, drawing links, interaction
- [ ] (Manfred/Edwin) Build execution engine to "run" an operation/node
- [x] (Shawn) Model-config component
- [x] (Edwin) Data component
- [ ] (Manfred) Simulate component
- [x] (Daniel) Calibrate component
- [x] (Edwin) support multiple or single node connections
