### ISSUE TITLE
[PLAN] Data

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/.github-private#5]
### Explorer
- [ ] integrate tables and figures search (Ahmed: https://github.com/DARPA-ASKEM/TERArium/issues/382)
- [ ] integrate url extractions (Ahmed: https://github.com/DARPA-ASKEM/TERArium/issues/357)
- [ ] integrate citation network - design first
- [ ] search titles and abstract by default (Ahmed: https://github.com/DARPA-ASKEM/TERArium/issues/355)
- [ ] default page (jumping point, big search box, types of search, would reduce load time) - design
- [ ] results (better metadata + image) - design
- [ ] matrix: (clustering, use RCM, zooming, feedback on selection, select row/column from headers, config panel)

### Papers
- [ ] retrieve open source pdf automatically
- [ ] upload paper?
- [ ] import web content with provenance?

### Data Service
- [ ] integrate dojo - upload dataset
- [ ] sample data instead of whole thing for performance? (please see the related issue https://github.com/DARPA-ASKEM/TERArium/issues/372)
- [ ] summary stats for each column
- [ ] annotation with DKG (transpose Jataware code from React -> Vue)
- [ ] database migration script automated

**Stakeholders**
- Jataware
- Ahmed M.
- Daniel C.
- David G
- Yohann P.
- Pascale P.
